CREATE TABLE public.datam3(
	customer_id text,
	gender text,
	age text,
	under_30 bool,
	senior_citizen bool,
	married bool,
	dependents bool,
	number_of_dependents int,
	country text,
	state text,
	city text,
	zip_code int,
	latitude float,
	longitude float,
	population int,
	quarter text,
	referred_a_friend bool,
	number_of_referrals int,
	tenure_in_months int,
	offer text,
	phone_service bool,
	avg_monthly_long_distance_charges float,
	multiple_lines bool,
	internet_service bool,
	internet_type text,
	avg_monthly_gb_download int,
	online_security bool,
	online_backup bool,
	device_protection_plan bool,
	premium_tech_support bool,
	streaming_tv bool,
	streaming_movies bool,
	streaming_music bool,
	unlimited_data bool,
	contract text,
	paperless_billing bool,
	payment_method text,
	monthly_charge float,
	total_charges float,
	total_refunds float,
	total_extra_data_charges int,
	total_long_distance_charges float,
	total_revenue float,
	satisfaction_score int,
	customer_status text,
	churn_label bool,
	churn_score int,
	cltv int,
	churn_category text,
	churn_reason text
);

copy datam3 FROM 'P2M3_Andryan_wijaya_data_raw.csv' CSV HEADER;

select * from datam3
